import turtle as t
t.color("blue")
t.shape("turtle")
t.pensize(3)
def tsifra(k):
    if k == 0:
        t.pendown()
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.penup()
    if k == 1:
        t.penup()
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.pendown()
        t.left(135)
        t.forward(70.7)
        t.right(135)
        t.forward(100)
        t.penup()
    if k == 2:
        t.penup()
        t.forward(50)
        t.left(180)
        t.pendown()
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.penup()
    if k == 3:
        t.penup()
        t.forward(50)
        t.left(180)
        t.pendown()
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.penup()
    if k == 4:
        t.penup()
        t.forward(50)
        t.left(90)
        t.pendown()
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.left(180)
        t.forward(100)
        t.penup()
    if k == 5:
        t.pendown()
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.penup
    if k == 6:
        t.pendown()
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.penup()
    if k == 7:
        t.pendown()
        t.forward(50)
        t.left(180)
        t.forward(50)
        t.right(135)
        t.forward(70.7)
        t.left(45)
        t.forward(50)
        t.penup()
    if k == 8:
        t.pendown()
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(100)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.penup()
    if k == 9:
        t.pendown()
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(50)
        t.right(180)
        t.forward(50)
        t.left(90)
        t.forward(100)

A = list(map(int, input().split()))
t.setup(1000, 200)
i = 0
for i in range(len(A)):
    t.penup()
    t.goto(- 400 + i * 100, 50)
    t.seth(180)
    tsifra(A[i])
    
    
